- name: mariadbをインストール
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python
    - mariadb
    - mariadb-server
    - libselinux-python

- name: 自動起動設定
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Rootユーザーの作成
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes

- name: eccubeユーザーを作成し,eccubeのデータベースに全ての権限を付与 
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: eccube
    password: "{{ mysql_db_password }}"
    priv: "eccube.*:ALL"
    host: localhost
    state: present

- name: check if pre-installed mariadb exists
  yum:
    list: mariadb-libs
  register: mariadb

# my.cnf
- name: check if my.cnf.bk already deployed
  stat:
    path: "/etc/my.cnf.bk"
  register: default_my_conf_backup

- name: deploy my.cnf
  template:
    src: "my.cnf.j2"
    dest: "/etc/my.cnf"
    owner: root
    group: root
    mode: 0644

# client.cnf
- name: check if client.cnf.bk already deployed
  stat:
    path: "/etc/my.cnf.d/client.cnf.bk"
  register: default_client_conf_backup

- name: deploy client.cnf
  template:
    src: "client.cnf.j2"
    dest: "/etc/my.cnf.d/client.cnf"
    owner: root
    group: root
    mode: 0644

# server.cnf
- name: check if server.cnf.bk already deployed
  stat:
    path: "/etc/my.cnf.d/server.cnf.bk"
  register: default_server_conf_backup

- name: deploy server.cnf
  template:
    src: "server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
    owner: root
    group: root
    mode: 0644

# server.cnf
- name: check if mysql-clients.cnf.bk already deployed
  stat:
    path: "/etc/my.cnf.d/mysql-clients.cnf.bk"
  register: default_mysql-clients_conf_backup

- name: deploy mysql-clients.cnf
  template:
    src: "mysql-clients.cnf.j2"
    dest: "/etc/my.cnf.d/mysql-clients.cnf"
    owner: root
    group: root
    mode: 0644

- name: create database [{{ __project_db_name }}]
  mysql_db:
    login_user: root
    login_password: "{{ __root_new_password }}"
    name: "{{ __project_db_name }}"
    state: present
    encoding: "{{ __project_db_encoding }}"
  when: __project_db_create

- name: create MySQL user [{{ __project_db_user_name }}] for database [{{ __project_db_name }}]
  mysql_user:
    login_user: root
    login_password: "{{ __root_new_password }}"
    user: "{{ __project_db_user_name }}"
    password: "{{ __project_db_user_password }}"
    host: localhost
    priv: "{{ __project_db_name }}.*:ALL,GRANT"
    state: present
  when: __project_db_create
