- name: yum install epel-repease
  yum: name=epel-release state=installed

- name: add remi-repo repository
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: install php 7.3
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip
    - php-process
    - php-pear
    - php-phpunit-PHPUnit
    - php-pecl-xdebug
    - php-intl
    - php-pecl-apc

- name: check if www.conf.bk already deployed
  stat:
    path: "/etc/php-fpm.d/www.conf.bk"
  register: default_www_conf_backup

- name: deploy www.conf.j2
  copy:
    src: "templates/www.conf.j2"
    dest: "/etc/php-fpm.d/www.conf"
    owner: root
    group: root
    mode: 0644

- name: Set autoload php-fpm
  become: true
  command: systemctl enable php-fpm

- name: restart php-fpm
  become: true
  command: systemctl restart php-fpm
