- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
  become_user: "{{ __working_user }}"

- name: set global rbenv path
  template:
    src: 001_rbenv.sh
    dest: ~/.bash.d/001_rbenv.sh
    mode: 0755
  become_user: "{{ __working_user }}"

- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  become_user: "{{ __working_user }}"

- name: check current ruby version
  shell: |
    /bin/bash -lc "ruby -v | grep -oP '^ruby \d{1}.\d{1}.\d{1}' | cut -f 2 -d ' '"
  register: current_ruby_version
  become_user: "{{ __working_user }}"
  changed_when: False

- name: shell relogin
  shell: |
    /bin/bash -lc  "source ~/.bash_profile"
  become_user: "{{ __working_user }}"
  when: current_ruby_version.stdout != __version

- name: install ruby
  shell: |
    /bin/bash -lc "rbenv install {{ __version }}"
    /bin/bash -lc "gem install bundler"
    /bin/bash -lc "rbenv rehash"
    /bin/bash -lc "rbenv local {{ __version }}"
  become_user: "{{ __working_user }}"
  when: current_ruby_version.stdout != __version

